USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE PROCEDURE "GENERATE_NUMERIC_CORRELATION_RULES"("DATASET_NAME" VARCHAR, "NUMERIC_COLS" ARRAY, "CORR_THRESHOLD" FLOAT DEFAULT 0.7)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('pandas', 'numpy', 'snowflake-snowpark-python')
HANDLER = 'generate_numeric_correlation_rules_handler'
EXECUTE AS OWNER
AS '';
