USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE PROCEDURE "VALIDATE_EQUATIONS_ON_DATA"("P_TABLE_NAME" VARCHAR, "P_EQUATIONS" VARCHAR, "P_TOLERANCE" FLOAT)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('pandas', 'numpy', 'snowflake-snowpark-python')
HANDLER = 'validate_equations_handler'
EXECUTE AS OWNER
AS '';
