USE DATABASE {{ snowflake_database }};
USE SCHEMA {{ snowflake_schema }};

CREATE STAGE DQ_FAILURES_STAGE
    DIRECTORY = (ENABLE = TRUE)
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') -- noqa: PRS
    COMMENT = 'To store the failed record as file';

ALTER TABLE DQ_DATASET_RUN_LOG
ADD COLUMN FAILED_FILE_URL VARCHAR();
