USE DATABASE {{ snowflake_database }};


USE SCHEMA {{ snowflake_schema }};

-- DDL for TABLE: MICROSEGMENT_PROFILER_ATTRIBUTE_SUMMARY
-- Extracted on: 2025-10-27 10:24:47
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE MICROSEGMENT_PROFILER_ATTRIBUTE_SUMMARY (
    MICROSEGMENT_PROFILER_SNAPSHOT_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_COLUMN_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_DEF_ID NUMBER(38, 0) NOT NULL,
    DATASET_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_ATTRIBUTE_DISTINCT_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_DISTINCT_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_IS_UNIQUE BOOLEAN,
    MICROSEGMENT_ATTRIBUTE_UNIQUE_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_UNIQUE_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_DATA_TYPE VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_IS_HASHABLE BOOLEAN,
    MICROSEGMENT_VALUE_COUNTS_NON_NULL VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_VALUE_COUNTS_SORTED VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_IS_ORDERED BOOLEAN,
    MICROSEGMENT_ATTRIBUTE_MISSING_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_TOTAL_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_MISSING_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_NON_NULL_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_MEMORY_SIZE_BYTES NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_FIRST_FEW_ROWS VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_MAX_LENGTH NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_AVG_LENGTH NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_MEDIAN_LENGTH NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_MIN_LENGTH NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_LENGTH_DISTRIBUTION VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_HISTOGRAM_LENGTH VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_DISTINCT_CHARACTER_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_TOTAL_CHARACTER_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_CHARACTER_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_CATEGORY_ALIASES VARCHAR(16777216),
    MICROSEGMENT_BLOCK_ALIASES VARCHAR(16777216),
    MICROSEGMENT_BLOCK_ALIAS_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_BLOCK_ALIAS_COUNT NUMBER(38, 0),
    MICROSEGMENT_BLOCK_ALIAS_CHARACTER_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_SCRIPT_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_SCRIPT_COUNT NUMBER(38, 0),
    MICROSEGMENT_SCRIPT_CHARACTER_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_CATEGORY_ALIAS_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_CATEGORY_COUNT NUMBER(38, 0),
    MICROSEGMENT_CATEGORY_ALIAS_CHARACTER_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_WORD_FREQUENCIES VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_INFERRED_DATA_TYPE VARCHAR(16777216),
    MICROSEGMENT_EXECUTION_DATE_START TIMESTAMP_NTZ(9),
    MICROSEGMENT_EXECUTION_DATE_END TIMESTAMP_NTZ(9),
    MICROSEGMENT_ATTRIBUTE_ALERT VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_NEGATIVE_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_NEGATIVE_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_INFINITE_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_ZERO_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_MEAN_VALUE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_STD_DEV NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_VARIANCE_VALUE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_MIN_VALUE VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_MAX_VALUE VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_KURTOSIS_VALUE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_SKEWNESS_VALUE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_SUM_VALUE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_MEAN_ABSOLUTE_DEVIATION NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_CHI_SQUARED_TEST VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_VALUE_RANGE VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_PERCENTILE_5 NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_PERCENTILE_25 NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_PERCENTILE_50 NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_PERCENTILE_75 NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_PERCENTILE_95 NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_INTERQUARTILE_RANGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_COEFFICIENT_OF_VARIATION NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_ZERO_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_INFINITE_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_MONOTONIC_INCREASING VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_MONOTONIC_DECREASING VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_STRICTLY_MONOTONIC_INCREASING VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_STRICTLY_MONOTONIC_DECREASING VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_MONOTONIC_TREND NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_VALUE_HISTOGRAM VARCHAR(16777216),
    MICROSEGMENT_ATTRIBUTE_DATA_IMBALANCE NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_INVALID_DATE_COUNT NUMBER(38, 0),
    MICROSEGMENT_ATTRIBUTE_INVALID_DATES_TOTAL NUMBER(18, 6),
    MICROSEGMENT_ATTRIBUTE_INVALID_DATES_PERCENTAGE NUMBER(18, 6),
    MICROSEGMENT_PROFILER_EXECUTION_DATE_START TIMESTAMP_NTZ(9),
    MICROSEGMENT_PROFILER_EXECUTION_DATE_END TIMESTAMP_NTZ(9),
    CREATED_BY VARCHAR(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_MICROSEGMENT_PROFILER_ATTRIBUTE_SUMMARY PRIMARY KEY (
        MICROSEGMENT_DEF_ID, DATASET_ID, MICROSEGMENT_PROFILER_SNAPSHOT_ID, MICROSEGMENT_COLUMN_ID
    )
);
-- DDL for TABLE: MICROSEGMENT_PROFILER_DATASET_SUMMARY
-- Extracted on: 2025-10-27 10:24:47
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE MICROSEGMENT_PROFILER_DATASET_SUMMARY (
    MICROSEGMENT_DEF_ID NUMBER(38, 0) NOT NULL,
    DATASET_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_PROFILER_SNAPSHOT_ID NUMBER(38, 0) NOT NULL,
    KPI_ID NUMBER(38, 0),
    MICROSEGMENT_TOTAL_RECORDS NUMBER(38, 0),
    MICROSEGMENT_TOTAL_COLUMNS NUMBER(38, 0),
    MICROSEGMENT_MEMORY_SIZE_BYTES NUMBER(38, 0),
    MICROSEGMENT_AVG_RECORD_SIZE_BYTES FLOAT,
    MICROSEGMENT_MISSING_VALUES_COUNT NUMBER(38, 0),
    MICROSEGMENT_COLUMNS_WITH_MISSING_VALUES NUMBER(38, 0),
    MICROSEGMENT_COLUMNS_FULLY_MISSING NUMBER(38, 0),
    MICROSEGMENT_MISSING_VALUES_PERCENTAGE FLOAT,
    MICROSEGMENT_COLUMN_DATA_TYPES VARCHAR(16777216),
    MICROSEGMENT_DUPLICATE_RECORDS_COUNT NUMBER(38, 0),
    MICROSEGMENT_DUPLICATE_RECORDS_PERCENTAGE FLOAT,
    MICROSEGMENT_PROFILER_EXECUTION_DATE_START TIMESTAMP_NTZ(9),
    MICROSEGMENT_PROFILER_EXECUTION_DATE_END TIMESTAMP_NTZ(9),
    CREATED_BY VARCHAR(100),
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SRC_MICROSEGMENT_PROFILER_DATASET_SUMMARY PRIMARY KEY (
        MICROSEGMENT_DEF_ID, DATASET_ID, MICROSEGMENT_PROFILER_SNAPSHOT_ID
    )
);
-- DDL for TABLE: DQ_CAT_REL_RULES
-- Extracted on: 2025-10-27 10:24:34
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE DQ_CAT_REL_RULES (
    DATASET_NAME VARCHAR(16777216),
    IF_COL VARCHAR(16777216),
    IF_VAL VARCHAR(16777216),
    THEN_COL VARCHAR(16777216),
    THEN_VAL VARCHAR(16777216),
    CONFIDENCE NUMBER(8, 3),
    SCORE NUMBER(5, 2),
    COLUMNS VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9)
);

-- DDL for TABLE: MICROSEGMENT_DETAILS
-- Extracted on: 2025-10-27 10:24:47
--------------------------------------------------------------------------------
CREATE OR REPLACE TABLE MICROSEGMENT_DETAILS (
    DATASET_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_EXECUTION_DATE_START TIMESTAMP_NTZ(9) NOT NULL,
    MICROSEGMENT_EXECUTION_DATE_END TIMESTAMP_NTZ(9) NOT NULL,
    MICROSEGMENT_DEF_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_ID NUMBER(38, 0) NOT NULL,
    MICROSEGMENT_PROFILE VARIANT,
    KPI_ID NUMBER(38, 0),
    MICROSEGMENT_PROFILER_SNAPSHOT_ID NUMBER(38, 0) NOT NULL,
    CONSTRAINT PK_MICROSEGMENT_DETAILS PRIMARY KEY (
        DATASET_ID, MICROSEGMENT_PROFILER_SNAPSHOT_ID, MICROSEGMENT_DEF_ID, MICROSEGMENT_ID
    )
);
