USE DATABASE {{ snowflake_database }};
USE SCHEMA {{ snowflake_schema }};



-- ADD missing columns
-- ALTER TABLE DQ_DATASET ADD COLUMN USER_ID NUMBER(38, 0);
-- ALTER TABLE DQ_DATASET ADD COLUMN SESSION_ID NUMBER(38, 0);
-- ALTER TABLE DQ_DATASET ADD COLUMN JUSTIFICATION VARCHAR(255);
-- ALTER TABLE DQ_DATASET ADD COLUMN THRESHOLD NUMBER(5, 2);

-- Above Statements were deployed already

-- -- MODIFY datatype mismatches
-- ALTER TABLE DQ_DATASET MODIFY COLUMN CREATED_BY NUMBER(38, 0);


-- CONVERT JSON columns to VARIANT
-- ALTER TABLE DQ_DATASET MODIFY COLUMN PRIMARY_KEY_COLUMNS VARIANT;
-- ALTER TABLE DQ_DATASET MODIFY COLUMN CANDIDATE_KEY_COLUMNS VARIANT;

--create dq_dataset_column table ---

CREATE OR REPLACE TABLE DQ_DATASET_COLUMN (
    COLUMN_ID NUMBER(38, 0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    DATASET_ID NUMBER(38, 0) NOT NULL,
    TRANS_LOGIC VARCHAR(16777216),
    COLUMN_KEY_TYPE VARCHAR(255),
    SCALE NUMBER(38, 0),
    PRECISION NUMBER(38, 0),
    DATA_TYPE VARCHAR(255),
    COLUMN_NAME VARCHAR(255),
    IS_CRITICAL_DATA_ELEMENT BOOLEAN,
    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CDE_COLUMN VARCHAR(255),
    DESCRIPTION VARCHAR(16777216),
    USER_ID NUMBER(38, 0),
    SESSION_ID NUMBER(38, 0),
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    IS_SELECTED BOOLEAN NOT NULL DEFAULT FALSE,
    JUSTIFICATION ARRAY,
    DESCRIPTION_JA VARCHAR(16777216),
    COLUMN_DOMAIN VARCHAR(16777216),
    CONSTRAINT DQ_DATASET_COLUMN_PKEY PRIMARY KEY (DATASET_ID, COLUMN_ID)
);
