USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW AIZU_TEST_DATA_2_DQ_FAILURE_VW (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    DV_CODE_SQL_CUSTOM_RULE_2759,
    "DV_CODE_Completeness_NOT_NULL_CHECK_2757",
    "DV_KEI_RIEKI_Numeric_MEAN_RANGE_CHECK_2761",
    DV_CODE_SQL_CUSTOM_RULE_2758,
    "DV_CODE_Completeness_NULL_CHECK_3421",
    DV_CODE_SQL_CUSTOM_RULE_2760,
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_VEND_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    329 AS DATASET_ID,
    'AIZU TEST DATA 2' AS DATASET_NAME,
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2759, 1, NULL)) = 0 AND MAX(rr_2759.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2759, 1, NULL)) = 0 AND MAX(rr_2759.IS_SUCCESS) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 2759, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2759",
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2757, 1, NULL)) = 0 AND MAX(rr_2757.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2757, 1, NULL)) = 0 AND MAX(rr_2757.IS_SUCCESS) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 2757, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_2757",
    CASE
        WHEN MAX(rr_2761.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN MAX(rr_2761.IS_SUCCESS) = FALSE THEN 'FAIL - AGGREGATE CHECK' ELSE 'PASS'
    END AS "DV_KEI_RIEKI_Numeric_MEAN_RANGE_CHECK_2761",
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2758, 1, NULL)) = 0 AND MAX(rr_2758.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2758, 1, NULL)) = 0 AND MAX(rr_2758.IS_SUCCESS) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 2758, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2758",
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3421, 1, NULL)) = 0 AND MAX(rr_3421.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3421, 1, NULL)) = 0 AND MAX(rr_3421.IS_SUCCESS) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 3421, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_Completeness_NULL_CHECK_3421",
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2760, 1, NULL)) = 0 AND MAX(rr_2760.IS_SUCCESS) IS NULL THEN 'NOT CONFIGURED' WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2760, 1, NULL)) = 0 AND MAX(rr_2760.IS_SUCCESS) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 2760, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2760",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_TEST_DATA_2_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr_2759 ON f.DATASET_RUN_ID = rr_2759.DATASET_RUN_ID AND rr_2759.RULE_CONFIG_ID = 2759
LEFT JOIN DQ_RULE_RESULTS rr_2757 ON f.DATASET_RUN_ID = rr_2757.DATASET_RUN_ID AND rr_2757.RULE_CONFIG_ID = 2757
LEFT JOIN DQ_RULE_RESULTS rr_2761 ON f.DATASET_RUN_ID = rr_2761.DATASET_RUN_ID AND rr_2761.RULE_CONFIG_ID = 2761
LEFT JOIN DQ_RULE_RESULTS rr_2758 ON f.DATASET_RUN_ID = rr_2758.DATASET_RUN_ID AND rr_2758.RULE_CONFIG_ID = 2758
LEFT JOIN DQ_RULE_RESULTS rr_3421 ON f.DATASET_RUN_ID = rr_3421.DATASET_RUN_ID AND rr_3421.RULE_CONFIG_ID = 3421
LEFT JOIN DQ_RULE_RESULTS rr_2760 ON f.DATASET_RUN_ID = rr_2760.DATASET_RUN_ID AND rr_2760.RULE_CONFIG_ID = 2760
GROUP BY ALL;
