USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW DQ_LAST_RUN_FAILED_RECORDS (
    DATASET_ID,
    DATASET_NAME,
    DATASET_RUN_ID,
    RULE_CONFIG_ID,
    FAILED_ROW,
    LOAD_TIMESTAMP
) AS
SELECT MAX_RUN.DATASET_ID AS DATASET_ID, DATASET_NAME, FAIL_REC1.*
FROM
    (
        SELECT CONFIG.DATASET_ID AS DATASET_ID, DS.DATASET_NAME, MAX(DATASET_RUN_ID) MAX_RUN_ID
        FROM DQ_FAILED_RECORDS AS FAIL_REC
        LEFT JOIN DQ_RULE_CONFIG AS CONFIG
            ON CONFIG.RULE_CONFIG_ID = FAIL_REC.RULE_CONFIG_ID
        LEFT JOIN DQ_DATASET AS DS
            ON DS.DATASET_ID = CONFIG.DATASET_ID
        GROUP BY CONFIG.DATASET_ID, DS.DATASET_NAME
    ) AS MAX_RUN
JOIN DQ_FAILED_RECORDS AS FAIL_REC1 ON FAIL_REC1.DATASET_RUN_ID = MAX_RUN.MAX_RUN_ID;
