USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW FAILED_RECORD_ANALYSIS (
    RULE_CONFIG_ID,
    MAXDATASET,
    FAILED_ROW
) AS
SELECT
    RULE_CONFIG_ID,
    DATASET_RUN_ID AS MaxDataset,
    FAILED_ROW
--ARRAY_SIZE(OBJECT_KEYS(FAILED_ROW)) AS Key_Count
FROM DQ_FAILED_RECORDS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RULE_CONFIG_ID
    ORDER BY
        DATASET_RUN_ID DESC,
        ARRAY_SIZE(OBJECT_KEYS(FAILED_ROW)) DESC
) = 1;
