USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_VENDOR_TEST_V4_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DV_DEAL_QTY_Schema_DATATYPE_CHECK(UNKNOWN)_3486",
    "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3488",
    "DV_K_NAME_Conformity_SET_INCLUSION_3477",
    "DV_DEAL_QTY_Uniqueness_UNIQUE_COUNT_RANGE_3487",
    "DV_DEAL_QTY_Numeric_MEAN_RANGE_CHECK_3480",
    "DV_DEAL_QTY_Numeric_MIN_RANGE_CHECK_3482",
    "DV_SEL_Completeness_NULL_CHECK_3475",
    "DV_NAME_Validity_PATTERN_EXCLUSION_3490",
    "DV_DEAL_QTY_Numeric_MEDIAN_RANGE_CHECK_3481",
    "DV_DEAL_QTY_Numeric_STDEV_RANGE_CHECK_3483",
    "DV_DEAL_QTY_Numeric_SUM_RANGE_CHECK_3484",
    "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3478",
    "DV_K_NAME_Validity_LENGTH_CHECK(0_14)_3489",
    "DV_CODE_Completeness_NOT_NULL_CHECK_3476",
    "DV_DEAL_QTY_Numeric_MAX_RANGE_CHECK_3479",
    "DV_BANK_Validity_SET_EXCLUSION_3491",
    "DV_DEAL_QTY_Schema_COLUMN_EXISTS_3485",
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_VEND_NAME,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    347 AS DATASET_ID,
    'AIZU_VENDOR_TEST_V4' AS DATASET_NAME,
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3486, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3486, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - SCHEMA CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Schema_DATATYPE_CHECK(UNKNOWN)_3486",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3488, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3488, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3488, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3488, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3488, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3488",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3477, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3477, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3477, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3477, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3477, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Conformity_SET_INCLUSION_3477",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3487, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3487, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Uniqueness_UNIQUE_COUNT_RANGE_3487",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3480, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3480, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MEAN_RANGE_CHECK_3480",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3482, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3482, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MIN_RANGE_CHECK_3482",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3475, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3475, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3475, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3475, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3475, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_SEL_Completeness_NULL_CHECK_3475",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3490, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3490, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3490, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3490, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3490, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NAME_Validity_PATTERN_EXCLUSION_3490",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3481, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3481, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MEDIAN_RANGE_CHECK_3481",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3483, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3483, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_STDEV_RANGE_CHECK_3483",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3484, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3484, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_SUM_RANGE_CHECK_3484",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3478, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3478, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3478, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3478, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3478, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3478",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3489, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3489, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3489, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3489, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3489, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Validity_LENGTH_CHECK(0_14)_3489",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3476, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3476, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3476, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3476, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3476, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_3476",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3479, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3479, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MAX_RANGE_CHECK_3479",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3491, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3491, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3491, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3491, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3491, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_Validity_SET_EXCLUSION_3491",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3485, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3485, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - SCHEMA CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Schema_COLUMN_EXISTS_3485",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_VENDOR_TEST_V4_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3486, 3488, 3477, 3487, 3480, 3482, 3475, 3490, 3481, 3483, 3484, 3478, 3489, 3476, 3479, 3491, 3485)
GROUP BY ALL;
