USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_POWERBI_MICROSEGMENT_ANALYSIS (
    DATASET_ID,
    KPI_ID,
    MICROSEGMENT_DEF_ID,
    MICROSEGMENT_PROFILER_SNAPSHOT_ID,
    MICROSEGMENT_ID,
    METRIC_VALUE,
    TIME_VALUE,
    CATEGORICAL_LEGEND,
    IS_ANOMALY,
    ANOMALY_DETECTION_METHOD,
    WITHIN_MICROSEGMENT_ANOMALY_REASON,
    WITHIN_MICROSEGMENT_ANOMALY_CONFIDENCE_SCORE
) AS
WITH RAW_ATTRIBUTES AS (
    -- 1. Flatten the VARIANT (JSON) column into individual rows
    -- This handles the "Long" format transformation
    SELECT
        D.DATASET_ID,
        D.KPI_ID,
        D.MICROSEGMENT_DEF_ID,
        D.MICROSEGMENT_PROFILER_SNAPSHOT_ID,
        D.MICROSEGMENT_ID,
        f.VALUE:attribute_name::STRING AS ATTRIBUTE_NAME,
        f.VALUE:attribute_value::STRING AS ATTRIBUTE_VALUE,
        -- Identifying the role of each attribute (Logic from your provided structure)
        f.VALUE:metric_column::STRING AS METRIC_COL_TAG,
        f.VALUE:time_column::STRING AS TIME_COL_TAG,
        f.VALUE:categorical_column::STRING AS CAT_COL_TAG
    FROM MICROSEGMENT_DETAILS D,
        LATERAL FLATTEN(input => D.MICROSEGMENT_PROFILE) f
),

PIVOTED_DATA AS (
    -- 2. Transform from Long to Wide so Power BI has one row per Microsegment_ID
    SELECT
        DATASET_ID,
        KPI_ID,
        MICROSEGMENT_DEF_ID,
        MICROSEGMENT_PROFILER_SNAPSHOT_ID,
        MICROSEGMENT_ID,
        -- Extract the Metric
        MAX(CASE WHEN METRIC_COL_TAG IS NOT NULL THEN TRY_TO_DOUBLE(ATTRIBUTE_VALUE) END) AS METRIC_VALUE,
        -- Extract the Time
        MAX(CASE WHEN TIME_COL_TAG IS NOT NULL THEN TRY_TO_DATE(ATTRIBUTE_VALUE) END) AS TIME_VALUE,
        -- Create the Legend by concatenating all categorical attributes
        LISTAGG(CASE WHEN CAT_COL_TAG IS NOT NULL THEN ATTRIBUTE_VALUE END, ' | ')
        WITHIN GROUP (ORDER BY ATTRIBUTE_NAME) AS CATEGORICAL_LEGEND
    FROM RAW_ATTRIBUTES
    GROUP BY 1, 2, 3, 4, 5
)

-- 3. Final Join with Anomalies
SELECT
    P.*,
    COALESCE(A.IS_WITHIN_ANOMALY, FALSE) OR COALESCE(A.IS_ACROSS_ANOMALY, FALSE) AS IS_ANOMALY,
    A.ANOMALY_DETECTION_METHOD,
    A.WITHIN_MICROSEGMENT_ANOMALY_REASON,
    A.WITHIN_MICROSEGMENT_ANOMALY_CONFIDENCE_SCORE
FROM PIVOTED_DATA P
LEFT JOIN MICROSEGMENT_ANOMALIES A
    ON
        P.DATASET_ID = A.DATASET_ID
        AND P.KPI_ID = A.KPI_ID
        AND P.MICROSEGMENT_DEF_ID = A.MICROSEGMENT_DEF_ID
        AND P.MICROSEGMENT_ID = A.MICROSEGMENT_ID
        AND P.MICROSEGMENT_PROFILER_SNAPSHOT_ID = A.MICROSEGMENT_PROFILER_SNAPSHOT_ID;
