USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_CONFORMITY_DISTRIBUTION_VALUE (
    DATASET_RUN_ID,
    DATASET_ID,
    RULE_CONFIG_ID,
    DATASET_NAME,
    COLUMN_NAME,
    REF_VALUE,
    COUNT_MATCH,
    NON_NULL_COUNT,
    RUN_DATE
) AS
WITH CONFORMITY_RESULTS AS (
    SELECT
        DATASET_RUN_ID,
        DATASET_ID,
        RULE_CONFIG_ID,
        DATASET_NAME,
        EXPECTATION_CONFIG:COLUMN_NAME::STRING AS COLUMN_NAME,
        OBSERVED_VALUE,
        ELEMENT_COUNT - MISSING_COUNT AS NON_NULL_COUNT,
        UNEXPECTED_COUNT,
        RUN_TIMESTAMP::DATE RUN_DATE,
        ROW_NUMBER() OVER (PARTITION BY RULE_CONFIG_ID ORDER BY DATASET_RUN_ID DESC) AS RN
    FROM DQ_RULE_RESULTS
    WHERE EXPECTATION_NAME = 'expect_column_values_to_be_in_set'
-- AND IS_SUCCESS = FALSE
-- AND DATASET_RUN_ID > 300
),
LATEST_RUNS AS (
    SELECT * FROM CONFORMITY_RESULTS WHERE RN = 1
)
SELECT
    r.DATASET_RUN_ID,
    r.DATASET_ID,
    r.RULE_CONFIG_ID,
    r.DATASET_NAME,
    r.COLUMN_NAME,
    f.KEY AS REF_VALUE,
    f.VALUE::NUMBER AS COUNT_MATCH,
    r.NON_NULL_COUNT,
    r.RUN_DATE
FROM LATEST_RUNS r,
    LATERAL FLATTEN(input => r.OBSERVED_VALUE) f

UNION ALL

SELECT
    r.DATASET_RUN_ID,
    r.DATASET_ID,
    r.RULE_CONFIG_ID,
    r.DATASET_NAME,
    r.COLUMN_NAME,
    'Others',
    r.UNEXPECTED_COUNT,
    r.NON_NULL_COUNT,
    r.RUN_DATE
FROM LATEST_RUNS r
WHERE r.UNEXPECTED_COUNT > 0

ORDER BY DATASET_RUN_ID DESC, (CASE WHEN REF_VALUE = 'Others' THEN 1 ELSE 0 END), COUNT_MATCH DESC;
