USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_TEST_DATA_2_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DV_CODE_Completeness_NULL_CHECK_3421",
    DV_CODE_SQL_CUSTOM_RULE_2758,
    "DV_KEI_RIEKI_Numeric_MEAN_RANGE_CHECK_2761",
    "DV_CODE_Completeness_NOT_NULL_CHECK_2757",
    DV_CODE_SQL_CUSTOM_RULE_2759,
    DV_CODE_SQL_CUSTOM_RULE_2760,
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_VEND_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    329 AS DATASET_ID,
    'AIZU TEST DATA 2' AS DATASET_NAME,
    CASE
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3421, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3421, rr.IS_SUCCESS, NULL)) IS NULL THEN NULL WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3421, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3421, rr.IS_SUCCESS, NULL)) IS NOT NULL
            THEN 'PASS'
        WHEN MAX(IFF(f.RULE_CONFIG_ID = 3421, 1, 0)) = 1 THEN 'FAIL' ELSE 'PASS'
    END AS "DV_CODE_Completeness_NULL_CHECK_3421",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2758, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2758, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2758, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2758, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2758, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2758",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 2761, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 2761, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_KEI_RIEKI_Numeric_MEAN_RANGE_CHECK_2761",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2757, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2757, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2757, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2757, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2757, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_2757",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2759, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2759, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2759, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2759, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2759, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2759",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2760, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2760, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2760, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2760, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2760, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2760",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_TEST_DATA_2_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3421, 2758, 2761, 2757, 2759, 2760)
GROUP BY ALL;
