USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_TEST_DATA_V4_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "COMPLIMENTARY_IND_Conformity_SET_INCLUSION_3390",
    TRANSACTION_DT_KEY_SQL_CUSTOM_RULE_3393,
    TRANSACTION_DT_KEY_SQL_CUSTOM_RULE_3392,
    TRANSACTION_DT_KEY,
    TRANSACTION_DT,
    MARKETPLACE_TYPE_CD,
    TRANSACTION_YEAR_MONTH_CD,
    REGION_CD,
    BM_REPORTING_REGION_CD,
    BM_REPORTING_REGION_NM,
    RETAIL_DAY_NBR,
    RETAIL_WEEK_NBR,
    RETAIL_WEEK_START_DT,
    RETAIL_WEEK_END_DT,
    RETAIL_MONTH_NBR,
    RETAIL_MONTH_START_DT,
    RETAIL_MONTH_END_DT,
    RETAIL_MONTH_DESC,
    RETAIL_QTR_NBR,
    RETAIL_QTR_DESC,
    RETAIL_QTR_START_DT,
    RETAIL_QTR_END_DT,
    RETAIL_SEASON_DESC,
    RETAIL_WEEK_SEASON_NBR,
    RETAIL_SEASON_NBR,
    RETAIL_SESN_START_DT,
    RETAIL_SESN_END_DT,
    RETAIL_YEAR_NBR,
    RETAIL_YEAR_START_DT,
    RETAIL_YEAR_END_DT,
    REPORTING_REGION_CD,
    REPORTING_REGION_SEGMENT_CD,
    MARKETPLACE_COUNTRY_NM,
    MARKETPLACE_ISO3_COUNTRY_CD,
    STORE_CD,
    STORE_GEO_NM,
    STORE_ENGLISH_NM,
    STORE_CITY_NM,
    STORE_CITY_TIER_NBR,
    STORE_GEOGRAPHY_REGION_NM,
    STORE_CHANNEL_ROLLUP_CD,
    STORE_DISTRICT_NM,
    STORE_TERRITORY_NM,
    STORE_POSTAL_CD,
    STORE_ERP_RETAIL_CONCEPT_CD,
    STORE_RETAIL_CONCEPT_DESC,
    CURRENCY_CD,
    MARKETPLACE_PLATFORM_CD,
    O2O_FLAG,
    REVENUE_RECOGNITION_DENOTATION,
    CONSUMER_DEMAND_GENERATION_DESC,
    CONSUMER_RETURN_LOCATION_DESC,
    ORDER_FULFILLMENT_METHOD_DESC,
    CONSUMER_COLLECTION_LOCATION_DESC,
    SHIP_TO_CITY_NM,
    SHIP_TO_STATE_CD,
    SHIP_TO_ZIP_CD,
    LINE_OF_BUSINESS_DESC,
    PRODUCT_UUID,
    PRODUCT_STYLE_CD,
    PRODUCT_CD,
    GTIN,
    NON_MERCH_IND,
    GIFT_CARD_IND,
    COMPLIMENTARY_IND,
    PRODUCT_FRANCHISE_NM,
    PRODUCT_COLOR_CD,
    PRODUCT_COLOR_DESC,
    PRODUCT_DIGITAL_DISPLAY_DESC,
    PRODUCT_CATEGORY_DESC,
    PRODUCT_UNIVERSAL_CATEGORY_DESC,
    PRODUCT_MERCHANDISING_CLASSIFICATION_DESC,
    PRODUCT_FRANCHISE_MERCH,
    PRODUCT_GENDER_DESC,
    PRODUCT_GENDER_AGE_DESC,
    PRODUCT_SILHOUETTE_DESC,
    PRODUCT_DIVISION_DESC,
    FIELDS_OF_PLAY_DESC,
    FIELDS_OF_PLAY_CODE,
    ORDER_ORIGIN,
    REPORTING_ORDER_ORIGIN_DESC,
    DEVICE,
    MARKETING_CHANNEL,
    CSR_IND,
    SEAMLESS_IND,
    PRODUCT_PLATFORM_DESC,
    PRODUCT_LEAGUE_NM,
    PRODUCT_TEAM_NM,
    PRODUCT_ATHLETE_NM,
    PRODUCT_PLANNING_DIVISION_NM,
    PRODUCT_PLANNING_AGE_GENDER_NM,
    PRODUCT_PLANNING_INTENDED_USE_NM,
    PRODUCT_PLANNING_STRUCTURE_NM,
    PRODUCT_PLANNING_SILHOUETTE_NM,
    PRODUCT_PLANNING_SUB_SILHOUETTE_NM,
    PRODUCT_BRAND_NM,
    PRODUCT_CONSUMER_CONSTRUCT_MWKJ,
    PRODUCT_CONSUMER_CONSTRUCT_SEGMENT_NM,
    PRODUCT_SUB_FAMILY_NM,
    PRODUCT_MODEL_NM,
    PRODUCT_CONSUMER_CONSTRUCT_DIMENSION_NM,
    PRODUCT_PLANNING_PERFORMANCE_ACTIVITY_NM,
    PRODUCT_PLANNING_PERFORMANCE_ACTIVITY_GROUP_NM,
    PRODUCT_PLANNING_FRANCHISE_PLANNING_PROGRAM_NM,
    PRODUCT_GLOBAL_REBUY_IND,
    PRICING_MSRP_PRC_USD,
    PRICING_MSRP_PRC,
    PRICING_CURRENT_SELLING_PRC_USD,
    PRICING_CURRENT_SELLING_PRC,
    VAT_TAX_AMT_USD,
    VAT_TAX_AMT,
    PRODUCT_STORE_REGULAR_ITEM_PRICE_USD,
    PRODUCT_STORE_REGULAR_ITEM_PRICE,
    TOTAL_GROSS_SALES_AMT_USD,
    TOTAL_GROSS_SALES_AMT,
    TOTAL_GROSS_SALES_QTY,
    TOTAL_CANCEL_AMT_USD,
    TOTAL_CANCEL_AMT,
    TOTAL_CANCEL_QTY,
    TOTAL_RETURN_AMT_USD,
    TOTAL_RETURN_AMT,
    TOTAL_RETURN_QTY,
    TOTAL_SHIPPED_AMT_USD,
    TOTAL_SHIPPED_AMT,
    TOTAL_SHIPPED_QTY,
    TOTAL_NET_SALES_AMT_USD,
    TOTAL_NET_SALES_AMT,
    TOTAL_NET_SALES_QTY,
    MARKDOWN_TOTAL_GROSS_SALES_AMT_USD,
    MARKDOWN_TOTAL_GROSS_SALES_AMT,
    PROMOTION_FULL_PRICE_GROSS_SALES_AMT_USD,
    PROMOTION_FULL_PRICE_GROSS_SALES_AMT,
    TOTAL_PROMO_GROSS_SALES_AMT_USD,
    TOTAL_PROMO_GROSS_SALES_AMT,
    COMPLIMENTARY_GROSS_SALES_AMT_USD,
    COMPLIMENTARY_GROSS_SALES_AMT,
    COMPLIMENTARY_GROSS_SALES_QTY,
    LOAD_DT
) AS
SELECT
    f.DATASET_RUN_ID,
    331 AS DATASET_ID,
    'AIZU TEST DATA V4' AS DATASET_NAME,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3390, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3390, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3390, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3390, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3390, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "COMPLIMENTARY_IND_Conformity_SET_INCLUSION_3390",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3393, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3393, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3393, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3393, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3393, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "TRANSACTION_DT_KEY_SQL_CUSTOM_RULE_3393",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3392, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3392, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3392, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3392, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3392, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "TRANSACTION_DT_KEY_SQL_CUSTOM_RULE_3392",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_TEST_DATA_V4_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3390, 3393, 3392)
GROUP BY ALL;
