USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_VENDOR_DATA_TEST_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2840,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2824,
    DV_NAME_SQL_CUSTOM_RULE_2793,
    DV_CURRENCY_SQL_CUSTOM_RULE_2831,
    DV_CODE_SQL_CUSTOM_RULE_2809,
    DV_BANK_SQL_CUSTOM_RULE_2799,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2837,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2823,
    DV_BUSI_CLASS_SQL_CUSTOM_RULE_2802,
    DV_BANK_SQL_CUSTOM_RULE_2830,
    DV_KEI_RIEKI_SQL_CUSTOM_RULE_2852,
    DV_K_NAME_SQL_CUSTOM_RULE_2815,
    "DV_KEN_NAME_Conformity_SET_INCLUSION_3444",
    DV_VEND_NAME_SQL_CUSTOM_RULE_2794,
    DV_CREATE_DT_SQL_CUSTOM_RULE_2857,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2848,
    DV_CURRENCY_SQL_CUSTOM_RULE_2800,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2838,
    DV_VEND_NAME_SQL_CUSTOM_RULE_2819,
    DV_NAME_SQL_CUSTOM_RULE_2814,
    DV_KEI_COST_SQL_CUSTOM_RULE_2851,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2825,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2821,
    DV_CURRENCY_SQL_CUSTOM_RULE_2833,
    DV_NO_SQL_CUSTOM_RULE_2861,
    DV_BUSI_CLASS_SQL_CUSTOM_RULE_2801,
    DV_CONTR_FLG_SQL_CUSTOM_RULE_2860,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2805,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2842,
    DV_CURRENCY_SQL_CUSTOM_RULE_2835,
    DV_BANK_SQL_CUSTOM_RULE_2829,
    DV_NO_SQL_CUSTOM_RULE_2863,
    DV_NO_SQL_CUSTOM_RULE_2864,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2839,
    DV_CURRENCY_SQL_CUSTOM_RULE_2834,
    DV_KEI_COST_SQL_CUSTOM_RULE_2806,
    DV_CODE_SQL_CUSTOM_RULE_2810,
    DV_NO_SQL_CUSTOM_RULE_2862,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2822,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2798,
    DV_CONTR_FLG_SQL_CUSTOM_RULE_2808,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2846,
    DV_K_NAME_SQL_CUSTOM_RULE_2816,
    DV_KEN_NAME_SQL_CUSTOM_RULE_2820,
    DV_VEND_NAME_SQL_CUSTOM_RULE_2797,
    DV_VEND_NAME_SQL_CUSTOM_RULE_2795,
    DV_CONTR_FLG_SQL_CUSTOM_RULE_2858,
    DV_NAME_SQL_CUSTOM_RULE_2813,
    DV_K_NAME_SQL_CUSTOM_RULE_2817,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2845,
    DV_KEI_COST_SQL_CUSTOM_RULE_2849,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2841,
    DV_PAY_METHOD_SQL_CUSTOM_RULE_2804,
    DV_KEI_RIEKI_SQL_CUSTOM_RULE_2854,
    DV_BANK_SQL_CUSTOM_RULE_2826,
    DV_NAME_SQL_CUSTOM_RULE_2811,
    DV_KEI_COST_SQL_CUSTOM_RULE_2850,
    DV_VEND_NAME_SQL_CUSTOM_RULE_2796,
    DV_CONTR_FLG_SQL_CUSTOM_RULE_2859,
    DV_KEI_RIEKI_SQL_CUSTOM_RULE_2853,
    DV_CURRENCY_SQL_CUSTOM_RULE_2832,
    DV_BANK_SQL_CUSTOM_RULE_2828,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2843,
    DV_BUSI_CLASS_SQL_CUSTOM_RULE_2803,
    DV_KEI_RIEKI_SQL_CUSTOM_RULE_2855,
    DV_VEND_NAME_SQL_CUSTOM_RULE_2818,
    DV_DEAL_KIN_SQL_CUSTOM_RULE_2847,
    DV_CODE_SQL_CUSTOM_RULE_2792,
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_VEND_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    332 AS DATASET_ID,
    'AIZU_VENDOR_DATA_TEST' AS DATASET_NAME,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2840, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2840, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2840, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2840, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2840, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2840",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2824, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2824, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2824, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2824, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2824, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2824",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2793, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2793, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2793, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2793, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2793, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NAME_SQL_CUSTOM_RULE_2793",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2831, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2831, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2831, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2831, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2831, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2831",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2809, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2809, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2809, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2809, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2809, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2809",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2799, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2799, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2799, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2799, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2799, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_SQL_CUSTOM_RULE_2799",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2837, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2837, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2837, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2837, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2837, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2837",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2823, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2823, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2823, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2823, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2823, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2823",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2802, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2802, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2802, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2802, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2802, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BUSI_CLASS_SQL_CUSTOM_RULE_2802",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2830, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2830, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2830, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2830, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2830, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_SQL_CUSTOM_RULE_2830",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2852, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2852, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2852, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2852, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2852, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_RIEKI_SQL_CUSTOM_RULE_2852",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2815, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2815, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2815, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2815, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2815, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_SQL_CUSTOM_RULE_2815",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3444, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3444, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3444, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3444, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3444, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_Conformity_SET_INCLUSION_3444",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2794, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2794, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2794, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2794, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2794, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2794",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2857, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2857, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2857, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2857, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2857, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CREATE_DT_SQL_CUSTOM_RULE_2857",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2848, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2848, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2848, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2848, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2848, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2848",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2800, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2800, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2800, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2800, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2800, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2800",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2838, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2838, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2838, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2838, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2838, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2838",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2819, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2819, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2819, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2819, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2819, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2819",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2814, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2814, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2814, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2814, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2814, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NAME_SQL_CUSTOM_RULE_2814",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2851, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2851, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2851, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2851, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2851, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_COST_SQL_CUSTOM_RULE_2851",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2825, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2825, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2825, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2825, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2825, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2825",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2821, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2821, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2821, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2821, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2821, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2821",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2833, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2833, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2833, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2833, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2833, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2833",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2861, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2861, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2861, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2861, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2861, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NO_SQL_CUSTOM_RULE_2861",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2801, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2801, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2801, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2801, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2801, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BUSI_CLASS_SQL_CUSTOM_RULE_2801",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2860, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2860, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2860, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2860, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2860, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CONTR_FLG_SQL_CUSTOM_RULE_2860",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2805, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2805, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2805, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2805, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2805, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2805",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2842, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2842, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2842, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2842, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2842, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2842",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2835, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2835, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2835, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2835, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2835, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2835",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2829, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2829, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2829, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2829, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2829, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_SQL_CUSTOM_RULE_2829",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2863, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2863, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2863, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2863, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2863, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NO_SQL_CUSTOM_RULE_2863",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2864, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2864, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2864, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2864, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2864, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NO_SQL_CUSTOM_RULE_2864",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2839, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2839, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2839, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2839, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2839, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2839",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2834, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2834, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2834, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2834, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2834, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2834",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2806, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2806, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2806, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2806, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2806, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_COST_SQL_CUSTOM_RULE_2806",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2810, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2810, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2810, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2810, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2810, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2810",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2862, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2862, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2862, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2862, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2862, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NO_SQL_CUSTOM_RULE_2862",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2822, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2822, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2822, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2822, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2822, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2822",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2798, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2798, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2798, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2798, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2798, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2798",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2808, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2808, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2808, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2808, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2808, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CONTR_FLG_SQL_CUSTOM_RULE_2808",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2846, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2846, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2846, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2846, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2846, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2846",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2816, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2816, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2816, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2816, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2816, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_SQL_CUSTOM_RULE_2816",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2820, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2820, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2820, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2820, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2820, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEN_NAME_SQL_CUSTOM_RULE_2820",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2797, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2797, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2797, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2797, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2797, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2797",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2795, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2795, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2795, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2795, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2795, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2795",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2858, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2858, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2858, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2858, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2858, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CONTR_FLG_SQL_CUSTOM_RULE_2858",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2813, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2813, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2813, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2813, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2813, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NAME_SQL_CUSTOM_RULE_2813",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2817, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2817, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2817, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2817, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2817, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_SQL_CUSTOM_RULE_2817",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2845, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2845, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2845, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2845, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2845, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2845",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2849, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2849, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2849, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2849, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2849, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_COST_SQL_CUSTOM_RULE_2849",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2841, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2841, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2841, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2841, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2841, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2841",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2804, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2804, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2804, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2804, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2804, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_SQL_CUSTOM_RULE_2804",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2854, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2854, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2854, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2854, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2854, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_RIEKI_SQL_CUSTOM_RULE_2854",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2826, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2826, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2826, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2826, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2826, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_SQL_CUSTOM_RULE_2826",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2811, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2811, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2811, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2811, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2811, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_NAME_SQL_CUSTOM_RULE_2811",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2850, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2850, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2850, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2850, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2850, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_COST_SQL_CUSTOM_RULE_2850",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2796, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2796, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2796, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2796, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2796, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2796",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2859, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2859, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2859, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2859, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2859, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CONTR_FLG_SQL_CUSTOM_RULE_2859",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2853, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2853, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2853, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2853, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2853, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_RIEKI_SQL_CUSTOM_RULE_2853",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2832, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2832, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2832, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2832, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2832, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CURRENCY_SQL_CUSTOM_RULE_2832",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2828, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2828, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2828, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2828, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2828, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_SQL_CUSTOM_RULE_2828",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2843, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2843, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2843, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2843, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2843, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2843",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2803, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2803, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2803, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2803, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2803, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BUSI_CLASS_SQL_CUSTOM_RULE_2803",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2855, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2855, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2855, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2855, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2855, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_KEI_RIEKI_SQL_CUSTOM_RULE_2855",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2818, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2818, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2818, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2818, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2818, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_VEND_NAME_SQL_CUSTOM_RULE_2818",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2847, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2847, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2847, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2847, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2847, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_DEAL_KIN_SQL_CUSTOM_RULE_2847",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 2792, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2792, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 2792, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 2792, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 2792, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_SQL_CUSTOM_RULE_2792",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_VENDOR_DATA_TEST_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (
            2840,
            2824,
            2793,
            2831,
            2809,
            2799,
            2837,
            2823,
            2802,
            2830,
            2852,
            2815,
            3444,
            2794,
            2857,
            2848,
            2800,
            2838,
            2819,
            2814,
            2851,
            2825,
            2821,
            2833,
            2861,
            2801,
            2860,
            2805,
            2842,
            2835,
            2829,
            2863,
            2864,
            2839,
            2834,
            2806,
            2810,
            2862,
            2822,
            2798,
            2808,
            2846,
            2816,
            2820,
            2797,
            2795,
            2858,
            2813,
            2817,
            2845,
            2849,
            2841,
            2804,
            2854,
            2826,
            2811,
            2850,
            2796,
            2859,
            2853,
            2832,
            2828,
            2843,
            2803,
            2855,
            2818,
            2847,
            2792
        )
GROUP BY ALL;
