USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_TEST_UPLOAD_CONFORMITY_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DV_BANK_Conformity_SET_INCLUSION_3449",
    "DV_PAY_METHOD_Conformity_SET_INCLUSION_3450",
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_VEND_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    337 AS DATASET_ID,
    'TEST_UPLOAD_CONFORMITY' AS DATASET_NAME,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3449, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3449, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3449, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3449, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3449, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_Conformity_SET_INCLUSION_3449",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3450, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3450, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3450, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3450, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3450, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_Conformity_SET_INCLUSION_3450",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM TEST_UPLOAD_CONFORMITY_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3449, 3450)
GROUP BY ALL;
