USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_TEST4_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    DQ_TIMESTAMP,
    "CC_MARKET_MANAGER_Completeness_NULL_CHECK_3543",
    "CC_CLASS_Completeness_NULL_CHECK_3544",
    CC_CALL_CENTER_SK,
    CC_CALL_CENTER_ID,
    CC_REC_START_DATE,
    CC_REC_END_DATE,
    CC_CLOSED_DATE_SK,
    CC_OPEN_DATE_SK,
    CC_NAME,
    CC_CLASS,
    CC_EMPLOYEES,
    CC_SQ_FT,
    CC_HOURS,
    CC_MANAGER,
    CC_MKT_ID,
    CC_MKT_CLASS,
    CC_MKT_DESC,
    CC_MARKET_MANAGER,
    CC_DIVISION,
    CC_DIVISION_NAME,
    CC_COMPANY,
    CC_COMPANY_NAME,
    CC_STREET_NUMBER,
    CC_STREET_NAME,
    CC_STREET_TYPE,
    CC_SUITE_NUMBER,
    CC_CITY,
    CC_COUNTY,
    CC_STATE,
    CC_ZIP,
    CC_COUNTRY,
    CC_GMT_OFFSET,
    CC_TAX_PERCENTAGE
) AS
SELECT
    f.DATASET_RUN_ID,
    381 AS DATASET_ID,
    'TEST4' AS DATASET_NAME,
    MAX(rr.RUN_TIMESTAMP) AS DQ_TIMESTAMP,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3543, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3543, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3543, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3543, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3543, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "CC_MARKET_MANAGER_Completeness_NULL_CHECK_3543",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3544, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3544, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3544, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3544, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3544, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "CC_CLASS_Completeness_NULL_CHECK_3544",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM TEST4_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3543, 3544)
GROUP BY ALL;
