USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_VENDOR_DATA_V2_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DV_OCCU_RATE_Numeric_SUM_RANGE_CHECK_3461",
    "DV_K_NAME_Conformity_SET_INCLUSION_3458",
    "DV_PAY_METHOD_Conformity_SET_INCLUSION_3457",
    "DV_DEAL_QTY_Numeric_SUM_RANGE_CHECK_3460",
    "DV_K_NAME_Completeness_NOT_NULL_CHECK_3466",
    "DV_CODE_Completeness_NOT_NULL_CHECK_3465",
    "DV_EST_RANK_Numeric_SUM_RANGE_CHECK_3462",
    "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3467",
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_VEND_NAME,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    345 AS DATASET_ID,
    'AIZU_VENDOR_DATA_V2' AS DATASET_NAME,
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3461, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3461, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_OCCU_RATE_Numeric_SUM_RANGE_CHECK_3461",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3458, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3458, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3458, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3458, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3458, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Conformity_SET_INCLUSION_3458",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3457, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3457, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3457, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3457, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3457, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_Conformity_SET_INCLUSION_3457",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3460, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3460, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_SUM_RANGE_CHECK_3460",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3466, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3466, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3466, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3466, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3466, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Completeness_NOT_NULL_CHECK_3466",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3465, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3465, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3465, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3465, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3465, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_3465",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3462, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3462, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_EST_RANK_Numeric_SUM_RANGE_CHECK_3462",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3467, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3467, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3467, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3467, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3467, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3467",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_VENDOR_DATA_V2_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3461, 3458, 3457, 3460, 3466, 3465, 3462, 3467)
GROUP BY ALL;
