USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_VENDOR_TEST_V3_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DV_K_NAME_Completeness_NOT_NULL_CHECK_3469",
    "DV_PAY_METHOD_Conformity_SET_INCLUSION_3471",
    "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3474",
    "DV_CODE_Completeness_NOT_NULL_CHECK_3468",
    "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3473",
    "DV_K_NAME_Conformity_SET_INCLUSION_3470",
    "DV_TR_CNT_Numeric_RANGE_CHECK(1_150)_3472",
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_VEND_NAME,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    346 AS DATASET_ID,
    'AIZU_VENDOR_TEST_V3' AS DATASET_NAME,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3469, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3469, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3469, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3469, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3469, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Completeness_NOT_NULL_CHECK_3469",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3471, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3471, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3471, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3471, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3471, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_PAY_METHOD_Conformity_SET_INCLUSION_3471",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3474, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3474, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3474, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3474, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3474, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3474",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3468, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3468, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3468, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3468, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3468, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_3468",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3473, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3473, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3473, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3473, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3473, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3473",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3470, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3470, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3470, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3470, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3470, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_K_NAME_Conformity_SET_INCLUSION_3470",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3472, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3472, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3472, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3472, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3472, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_TR_CNT_Numeric_RANGE_CHECK(1_150)_3472",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_VENDOR_TEST_V3_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3469, 3471, 3474, 3468, 3473, 3470, 3472)
GROUP BY ALL;
