USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_CONFORMITY_DIMENSION (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    RULE_CONFIG_ID,
    RULE_DESCRIPTION,
    IS_SUCCESS,
    REFERENTIAL_SET,
    ELEMENT_COUNT,
    MISSING_COUNT,
    NON_NULL_COUNT,
    MATCH_COUNT,
    UNEXPECTED_COUNT,
    DISTINCT_MATCH_COUNT,
    TOTAL_REFERENCE_COUNT,
    RUN_DATE,
    RUN_TIME
) AS
WITH RANKED_RESULTS AS (
    SELECT
        DRR.DATASET_RUN_ID,
        DRR.DATASET_ID,
        DRR.DATASET_NAME,
        DRR.RULE_CONFIG_ID,
        DEM.DESCRIPTION AS RULE_DESCRIPTION,
        DRR.IS_SUCCESS,
        DRR.EXPECTATION_CONFIG:KWARGS:value_set::STRING AS REFERENTIAL_SET,
        DRR.ELEMENT_COUNT,
        DRR.MISSING_COUNT,
        (DRR.ELEMENT_COUNT - DRR.MISSING_COUNT) AS NON_NULL_COUNT,
        DRR.RESULTS:match_count::NUMBER AS MATCH_COUNT,
        DRR.UNEXPECTED_COUNT,
        DRR.RESULTS:distinct_match_count::NUMBER AS DISTINCT_MATCH_COUNT,
        DRR.RESULTS:total_reference_values::NUMBER AS TOTAL_REFERENCE_COUNT,
        DRR.RUN_TIMESTAMP::DATE AS RUN_DATE,
        DRR.RUN_TIMESTAMP::TIMESTAMP AS RUN_TIME,
        ROW_NUMBER() OVER (PARTITION BY DRR.RULE_CONFIG_ID ORDER BY DRR.run_timestamp DESC) AS RN
    FROM DQ_RULE_RESULTS AS DRR JOIN DQ_EXPECTATION_MASTER AS DEM ON DRR.EXPECTATION_ID = DEM.EXPECTATION_ID
    WHERE EXPECTATION_NAME = 'expect_column_values_to_be_in_set'
)
SELECT
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    RULE_CONFIG_ID,
    RULE_DESCRIPTION,
    IS_SUCCESS,
    REFERENTIAL_SET,
    ELEMENT_COUNT,
    MISSING_COUNT,
    NON_NULL_COUNT,
    MATCH_COUNT,
    UNEXPECTED_COUNT,
    DISTINCT_MATCH_COUNT,
    TOTAL_REFERENCE_COUNT,
    RUN_DATE,
    RUN_TIME
FROM RANKED_RESULTS
WHERE RN = 1
ORDER BY DATASET_RUN_ID DESC;
