USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_AIZU_VENDOR_NEW_V1_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    DQ_TIMESTAMP,
    "DV_KEI_COST_Schema_COLUMN_EXISTS_3525",
    "DV_BANK_Conformity_SET_INCLUSION_3520",
    "DV_CODE_Completeness_NOT_NULL_CHECK_3521",
    "DV_DEAL_QTY_Numeric_MAX_RANGE_CHECK_3523",
    "DV_DEAL_QTY_Numeric_MEAN_RANGE_CHECK_3524",
    "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3526",
    "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3522",
    DV_CODE,
    DV_NAME,
    DV_K_NAME,
    DV_KEN_NAME,
    DV_BANK,
    DV_CURRENCY,
    DV_TEL,
    DV_C_TEL,
    DV_C_NAME,
    DV_BUSI_CLASS,
    DV_PAY_METHOD,
    DV_DEAL_QTY,
    DV_DEAL_KIN,
    DV_URI_KIN,
    DV_EST_PRIC,
    DV_KEI_COST,
    DV_KEI_RIEKI,
    DV_TAX_REM,
    DV_SHORT_LOAN_1,
    DV_LONG_LOAN_1,
    DV_TOT_LOAN_1,
    DV_SIHON,
    DV_SISAN,
    DV_TR_CNT,
    DV_TR_SUM_SU,
    DV_OCCU_RATE,
    DV_CREATE_DT,
    DV_CHANGE_DT,
    DV_LAST_BUSI_DT,
    DV_VEND_NAME,
    DV_EST_RANK,
    DV_SYNC_GROUP,
    DV_CONTR_FLG,
    DV_SEL,
    DV_NO
) AS
SELECT
    f.DATASET_RUN_ID,
    364 AS DATASET_ID,
    'AIZU_VENDOR_NEW_V1' AS DATASET_NAME,
    MAX(rr.RUN_TIMESTAMP) AS DQ_TIMESTAMP,
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3525, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3525, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - SCHEMA CHECK'
        ELSE 'PASS'
    END AS "DV_KEI_COST_Schema_COLUMN_EXISTS_3525",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3520, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3520, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3520, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3520, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3520, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_BANK_Conformity_SET_INCLUSION_3520",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3521, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3521, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3521, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3521, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3521, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Completeness_NOT_NULL_CHECK_3521",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3523, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3523, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MAX_RANGE_CHECK_3523",
    CASE
        WHEN MAX(IFF(rr.RULE_CONFIG_ID = 3524, rr.IS_SUCCESS, NULL)) IS NULL THEN 'NOT CONFIGURED' WHEN
            MAX(IFF(rr.RULE_CONFIG_ID = 3524, rr.IS_SUCCESS, NULL)) = FALSE
            THEN 'FAIL - AGGREGATE CHECK'
        ELSE 'PASS'
    END AS "DV_DEAL_QTY_Numeric_MEAN_RANGE_CHECK_3524",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3526, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3526, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3526, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3526, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3526, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_CODE_Uniqueness_UNIQUENESS_CHECK_3526",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3522, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3522, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3522, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3522, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3522, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DV_OCCU_RATE_Numeric_RANGE_CHECK(0_100)_3522",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM AIZU_VENDOR_NEW_V1_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3525, 3520, 3521, 3523, 3524, 3526, 3522)
GROUP BY ALL;
