USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_CONFORMITY_DIMENSION (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    RULE_CONFIG_ID,
    IS_SUCCESS,
    REFERENTIAL_SET,
    ELEMENT_COUNT,
    MISSING_COUNT,
    NON_NULL_COUNT,
    MATCH_COUNT,
    UNEXPECTED_COUNT,
    DISTINCT_MATCH_COUNT,
    TOTAL_REFERENCE_COUNT,
    RUN_DATE,
    RUN_TIME
) AS
WITH RANKED_RESULTS AS (
    SELECT
        DATASET_RUN_ID,
        DATASET_ID,
        DATASET_NAME,
        RULE_CONFIG_ID,
        IS_SUCCESS,
        expecation_config:KWARGS:value_set::STRING AS REFERENTIAL_SET,
        ELEMENT_COUNT,
        MISSING_COUNT,
        (ELEMENT_COUNT - MISSING_COUNT) AS NON_NULL_COUNT,
        RESULTS:match_count::NUMBER AS MATCH_COUNT,
        UNEXPECTED_COUNT,
        RESULTS:distinct_match_count::NUMBER AS DISTINCT_MATCH_COUNT,
        RESULTS:total_reference_values::NUMBER AS TOTAL_REFERENCE_COUNT,
        run_timestamp::DATE AS RUN_DATE,
        run_timestamp::TIMESTAMP AS RUN_TIME,
        ROW_NUMBER() OVER (PARTITION BY RULE_CONFIG_ID ORDER BY run_timestamp DESC) AS RN
    FROM DQ_RULE_RESULTS
    WHERE EXPECTATION_NAME = 'expect_column_values_to_be_in_set'
)
SELECT
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    RULE_CONFIG_ID,
    IS_SUCCESS,
    REFERENTIAL_SET,
    ELEMENT_COUNT,
    MISSING_COUNT,
    NON_NULL_COUNT,
    MATCH_COUNT,
    UNEXPECTED_COUNT,
    DISTINCT_MATCH_COUNT,
    TOTAL_REFERENCE_COUNT,
    RUN_DATE,
    RUN_TIME
FROM RANKED_RESULTS
WHERE RN = 1
ORDER BY DATASET_RUN_ID DESC;
