USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_TEST_AIZU_1M_DQ_FAILURE (
    DATASET_RUN_ID,
    DATASET_ID,
    DATASET_NAME,
    "DP_CHG_COST_Numeric_RANGE_CHECK(100_999)_3453",
    "DP_PART_NO_Completeness_NULL_CHECK_3452",
    DP_PART_NO,
    DP_ENG_REL_NO,
    DP_ENG_DESC,
    DP_ENG_REL_DT,
    DP_PLAN_NO,
    DP_CREATE_DT,
    DP_SOURCE,
    DP_PART_CLASS,
    DP_ABC,
    DP_ABC_TYP,
    DP_DATA_TYP,
    DP_CTRL_KBN,
    DP_SOH,
    DP_UNCOM_ORD,
    DP_COM_ORD,
    DP_FORE_RES,
    DP_REORD,
    DP_EOQ_TIME,
    DP_PAN_SIZE,
    DP_ORD_POL,
    DP_LEAD_TIME,
    DP_VER_DT,
    DP_KTAN_1,
    DP_KTAN_2,
    DP_STAN_1,
    DP_STAN_2,
    DP_UTAN_1,
    DP_UTAN_2,
    DP_PL_SET_COST,
    DP_PL_MFG_COST,
    DP_PL_MAT_COST,
    DP_CH_SET_COST,
    DP_CH_MFG_COST,
    DP_CH_MAT_COST,
    DP_CHG_COST,
    DP_COST_FLG,
    DP_MFG_HR_HUD,
    DP_SET_HR,
    DP_MOVE_HR,
    DP_SHRINK,
    DP_CMP_SHRINK,
    DP_ACT_SHRINK,
    DP_MFG_TYPE,
    DP_MAKE_RANK,
    DP_VEND_1,
    DP_VEND_2,
    DP_DEST_AREA,
    DP_STOCK_AREA,
    DP_LOCATE,
    DP_PLANT,
    DP_IMPORT_KBN,
    DP_TAX_CD,
    DP_CURRENCY_UNIT,
    DP_COCOM_PARTS
) AS
SELECT
    f.DATASET_RUN_ID,
    344 AS DATASET_ID,
    'TEST_AIZU_1M' AS DATASET_NAME,
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3453, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3453, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3453, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3453, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3453, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DP_CHG_COST_Numeric_RANGE_CHECK(100_999)_3453",
    CASE
        WHEN
            COUNT(IFF(f.RULE_CONFIG_ID = 3452, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3452, rr.IS_SUCCESS, NULL)) IS NULL
            THEN 'NOT CONFIGURED'
        WHEN COUNT(IFF(f.RULE_CONFIG_ID = 3452, 1, NULL)) = 0 AND MAX(IFF(rr.RULE_CONFIG_ID = 3452, rr.IS_SUCCESS, NULL)) IS NOT NULL THEN 'PASS' WHEN
            MAX(IFF(f.RULE_CONFIG_ID = 3452, 1, 0)) = 1
            THEN 'FAIL'
        ELSE 'PASS'
    END AS "DP_PART_NO_Completeness_NULL_CHECK_3452",
    f.* EXCLUDE (RULE_CONFIG_ID, DATASET_RUN_ID, DATASET_ID, DQ_LOAD_TIMESTAMP)
FROM TEST_AIZU_1M_DQ_FAILURE f
LEFT JOIN DQ_RULE_RESULTS rr
    ON
        f.DATASET_RUN_ID = rr.DATASET_RUN_ID
        AND rr.RULE_CONFIG_ID IN (3453, 3452)
GROUP BY ALL;
