USE DATABASE {{ snowflake_database }};

USE SCHEMA {{ snowflake_schema }};

CREATE OR REPLACE VIEW VW_LATEST_DQ_RUNS (
    DATASET_ID,
    DATASET_RUN_ID,
    RNK
) AS
SELECT DATASET_ID, DATASET_RUN_ID, DENSE_RANK() OVER (PARTITION BY DATASET_ID ORDER BY DATASET_RUN_ID DESC) AS RNK
FROM (SELECT DATASET_ID, DATASET_RUN_ID FROM DQ_RULE_RESULTS GROUP BY ALL) ORDER BY 1, 3;
