USE DATABASE {{ snowflake_database }};
USE SCHEMA {{ snowflake_schema }};

ALTER TABLE DQ_RULE_CONFIG
ADD COLUMN CREATED_AT TIMESTAMP_NTZ;

ALTER TABLE DQ_RULE_CONFIG
ADD COLUMN UPDATED_AT TIMESTAMP_NTZ;

ALTER TABLE DQ_RULE_CONFIG
ADD COLUMN RULE_CONFIG_SESSION_ID INT;

ALTER TABLE DQ_DATASET_COLUMN
RENAME COLUMN PRECISION TO PRECISION_VALUE;
